DMR\\Bundle\\PaginatorBundle\\Paginator\\PaginatorInterface:
  exclusion_policy: ALL
  virtual_properties:
    getCurrentPage:
      serialized_name: page
    getNumberItemsPerPage:
      serialized_name: itemsPerPage
    getCountItems:
      serialized_name: total_items_count
    getCountPages:
      serialized_name: pages_count